sync_address = "https://atuin.daveynet.xyz"
sync_frequency = "1m"
keymap_mode = "auto"
style = "auto"

history_filter = ["set .*API.*"]
search_mode = "daemon-fuzzy"

[daemon]
enabled = true
autostart = true
